version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - export TF_WORKSPACE="${tf_workspace}"
      - export TF_WORKSPACE_LOWER="${tf_workspace_lower}"
      - export REPOSITORY_NAME="${repository_name}"
      - export GITHUB_TOKEN="${github_token}"
      - export BRANCH=master
      - export PROJECT_NAME=${project_name}
      - export ACCOUNT_NAME_RAW="$(sh /account_name_from_branch.sh)"
      - export ACCOUNT_NAME="$(echo $ACCOUNT_NAME_RAW | awk '{print tolower($0)}')"
      - export NODE_ENV="${node_env}"
      - . ./buildspecs/buildspec-terraform.sh
