version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - export TF_WORKSPACE="${tf_workspace}"
      - export GITHUB_TOKEN="${github_token}"
      - export REPO="${repository_name}"
      - . ./buildspecs/buildspec-code.sh
artifacts:
  files: # what's needed for the terraform deploy
    - '**/*'
